[package]
name = "stomp-parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.65"

[dependencies]
winnow = { version = "= 0.6" }

[dev-dependencies]
assert_matches2 = "0.1"
pretty_assertions = { version = "1" }

