[package]
name = "stomp-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
nom = "7"

[dev-dependencies]
pretty_assertions = { version = "1", features = ["unstable"] }
