name: Find the minimum supported Rust version

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [
            #
            ubuntu-latest,
            # windows-latest,
            macOS-latest,
          ]
        rust_toolchain: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          components: clippy, rustfmt
      - name: Build
        run: cargo build --verbose
      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv
      - name: Find the minimum supported Rust version
        run: cargo msrv find --output-format json --log-level debug
      - run: cargo msrv verify --output-format json --log-level debug
